sudo: required
language: python
matrix:
    include:
        # check code style and Python 3.6
        - python: 3.6
          env: TEST_MODE=PEP8
        # run tests with keras from source and Python 3.6
        - python: 3.6
          env: KERAS_HEAD=true
          env: TEST_MODE=TESTS
        # run tests with keras from PyPI and Python 3.6
        - python: 3.6
          env: TEST_MODE=TESTS
        # run import test and Python 3.6
        - python: 3.6
          env: TEST_MODE=IMPORTS


before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

install:
  - if [[ $KERAS_HEAD == "true" ]]; then
      pip install --no-deps git+https://github.com/keras-team/keras.git --upgrade;
    fi
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
      pip install -e .[pep8];
    elif [[ "$TEST_MODE" == "TESTS" ]]; then
      pip install -e .[tests];
    elif [[ "$TEST_MODE" == "IMPORTS" ]]; then
      pip install .;
    fi

script:
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
      flake8 -v --count;
    elif [[ "$TEST_MODE" == "TESTS" ]]; then
      py.test tests --cov-config .coveragerc --cov=keras_preprocessing tests;
    elif [[ "$TEST_MODE" == "IMPORTS" ]]; then
      python -c "import keras_preprocessing; from keras_preprocessing import image; from keras_preprocessing import sequence; from keras_preprocessing import text";
    fi
